name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Roda o workflow em push para a branch 'master'
  pull_request:
    branches:
      - master # Roda o workflow em pull requests para a branch 'master'

jobs:
  build-and-test:
    runs-on: ubuntu-latest # O sistema operacional onde o job será executado

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Clona o seu repositório

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Define a versão do Node.js a ser usada (ajuste conforme necessário)

    - name: Install Dependencies
      run: npm ci --legacy-peer-deps # Instala as dependências do projeto (npm ci é mais rápido e seguro em CIs)

    # - name: Compile TypeScript
    #   run: npx tsc # Executa o compilador TypeScript

    - name: Run Tests
      run: npm run test # Executa os scripts de teste definidos no seu package.json